spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://order-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    import: "classpath:application-jpa.yml"

server:
  port: 10023

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/
