version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ticketping/eureka-server

  auth-server:
    build:
      context: ./auth
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ticketping/auth-server

  gateway-server:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ticketping/gateway-server

  user-server:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ticketping/user-server

  performance-server:
    build:
      context: ./services/performance
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ticketping/performance-server

  order-server:
    build:
      context: ./services/order
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ticketping/order-server

  payment-server:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ticketping/payment-server

  queue-manage-server:
    build:
      context: ./services/queue-manage
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ticketping/queue-manage-server