spring:
  application:
    name: gateway
  profiles:
    include: private
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - PATCH
              - OPTIONS

  data:
    redis:
     host: redis
     port: 6379

server:
  port: 10020

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/

token-value:
  secret-key: secret-key