spring:
  application:
    name: gateway

  data:
    redis:
     host: redis
     port: 6379

server:
  port: 10020

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/

token-value:
  secret-key: secret-key