### Order 생성 요청
POST http://localhost:10023/api/v1/orders
Content-Type: application/json
X_USER_ID: f47ac10b-58cc-4372-a567-0e02b2c3d479

{
  "scheduleId": "869df884-454c-4b67-a8e5-4572a3803a5d",
  "seatId": "6a861199-c928-42e4-aeb0-82d8dcef1866"
}

### performance 좌석 주문 정보 조회 요청
GET http://localhost:10022/api/v1/seats/0c617eaf-6993-4820-9fea-0be4843e3154/order-info
Content-Type: application/json
