spring:
  application:
    name: auth
  profiles:
    include: private
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 10010

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/