spring:
  application:
    name: auth
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 10010

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    enabled: true

jwt:
  secret: ${JWT_SECRET_KEY}