spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://payment-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    import: "classpath:application-jpa.yml"

server:
  port: 10024

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/

stripe:
  secret-key: ${SECRET_KEY}
  public-key: ${PUBLIC_KEY}

