spring:
  application:
    name: payment

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketping
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

server:
  port: 8080

stripe:
  secret-key: ${secret-key}
  public-key: ${public-key}
  webhook-key: ${WEBHOOK_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/