spring:
  application:
    name: payment
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketping
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

payment:
  toss:
    test_client_api_key : test_ck_DpexMgkW36bObXqBW4Nd3GbR5ozO
    test_secret_api_key : test_sk_jExPeJWYVQ4qevAzYeaq349R5gvN
    success_url : "http://localhost:8080/api/v1/payments/toss/success"
    fail_url : "http://localhost:8080/api/v1/payments/toss/fail"
    origin_url: "https://api.tosspayments.com/v1/payments/"

