spring:
  application:
    name: performance
  datasource:
    url: jdbc:postgresql://performance-db:5432/postgres
#    url: jdbc:postgresql://localhost:5432/ticketping-performance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    import: "classpath:application-jpa.yml"
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 10022

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/


