spring:
  application:
    name: performance
  datasource:
    url: jdbc:postgresql://performance-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    import: "classpath:application-jpa.yml"
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 10022

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    enabled: true