spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://user-db:5432/postgres
#    url: jdbc:postgresql://localhost:5432/ticketping-user
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  base-package:
    jpa: com.ticketPing.performance.domain.entity
  config:
    import: "classpath:application-jpa.yml"

server:
  port: 10021

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/